### ISSUE TITLE
Recommended faucet not working

### ISSUE THREAD

**Issue by reiven** [Dirrot/dogecoin-testnet#6]
Hi, the tesnet faucet suggested in the Readme (testdoge.lionservers.de) is not working.
Also, i cannot get any coin from mining on testnet. 
I've used block.io which give you some testnet coins for XBT/LTC/XDG

**Comment by Dirrot** [comment]
Hi, i look into the issue with testdoge.lionserver.de within the next days. If you have any questions relying to the dogencoin-testnet - i need you to take a look at reddit http://www.reddit.com/r/dogecoindev 

You definitly reach more people, who are familiar with the dogecoin-test net as in here..
